### ISSUE TITLE
时间输入框无法赋值

### ISSUE THREAD

**Issue by wanzizi** [wanwu-fe/vue-json-schema-form#2]
版本：v1.0.9

当前效果：
![BB153D4F-40B3-4C04-860C-A5BA876837C2](https://user-images.githubusercontent.com/13686739/87265045-3ba5b000-c4f4-11ea-8232-7b28bc605730.png)
![1B9BAF73-A513-4D25-A251-805C20D1CA0B](https://user-images.githubusercontent.com/13686739/87265077-58da7e80-c4f4-11ea-8ba4-24dd2668e1d5.png)

数据好像没有传到date组件

预期效果：选择时间之后可以正确显示

**Comment by Jokcy** [comment]
fixed at 1.0.10
